-- ============================================
-- TCG Market Intelligence - Supabase Schema
-- Run this SQL in Supabase SQL Editor
-- ============================================

-- 1. Master table (source of truth for all cards).
-- The `id` is a deterministic, human-readable string generated by the
-- frontend (and scraper/bulk loader) using the formula:
--   PTCG: 'ptcg' + series + digits(card_index) + lowercase(rarity) + yuyutei_slug
--   OPCG: 'opcg' + digits(card_index) + letters-only-lowercase(rarity) + yuyutei_slug
-- See src/lib/cardId.ts for the canonical implementation.
CREATE TABLE IF NOT EXISTS master_table (
  id TEXT PRIMARY KEY,
  tcg_type TEXT NOT NULL CHECK (tcg_type IN ('PTCG', 'OPCG')),
  card_series TEXT NOT NULL,
  card_index TEXT NOT NULL,
  card_name TEXT NOT NULL DEFAULT '',
  card_rarity TEXT NOT NULL,
  url_yuyutei TEXT,
  -- SNKRDUNK apparel id (e.g. '515454'). Discovered lazily by the daily scraper
  -- and cached here so the next run skips the discovery step.
  snkrdunk_apparel_id TEXT,
  -- Validation subpage on /database/validation. Set by the human after
  -- they confirm the mapping is correct against the live SNKRDUNK page.
  verified_at     TIMESTAMPTZ NULL,
  verify_status   TEXT NULL
    CHECK (verify_status IS NULL OR verify_status IN ('verified', 'rejected')),
  created_at TIMESTAMPTZ DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON master_table TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON master_table TO service_role;

CREATE INDEX IF NOT EXISTS idx_master_table_snkrdunk_apparel
  ON master_table(snkrdunk_apparel_id) WHERE snkrdunk_apparel_id IS NOT NULL;

-- Validation queue: cards with apparel_id but no human verdict yet
CREATE INDEX IF NOT EXISTS idx_master_table_verify_queue
  ON master_table (snkrdunk_apparel_id)
  WHERE snkrdunk_apparel_id IS NOT NULL AND verify_status IS NULL;

-- 2. Price history (populated by scraper)
--
-- Each row is one historical sale (source='jp', JPY + true sale date) OR
-- one current EN listing snapshot (source='en', HKD + scrape date = today).
-- Only PSA 10 and A (RAW_A) conditions are stored, mapped to the app enum
-- in src/lib/types.ts. The legacy `price` column is kept (always JPY) so the
-- existing frontend reads (WatchlistPage, InventoryPage, DashboardPage) keep
-- working without changes; the change% math stays correct because every row's
-- `price` is in the same currency.
--
-- Migration note: this is a destructive overwrite. If the old table has data
-- you want to preserve, dump it first:
--   supabase db dump --table price_history > price_history.old.sql
CREATE TABLE IF NOT EXISTS price_history (
  id            UUID         DEFAULT gen_random_uuid() PRIMARY KEY,
  card_id       TEXT         NOT NULL REFERENCES master_table(id) ON DELETE CASCADE,
  source        TEXT         NOT NULL CHECK (source IN ('jp', 'en')),
  condition     TEXT         NOT NULL CHECK (condition IN ('PSA10', 'RAW_A')),
  observed_date DATE         NOT NULL,
  price         INTEGER      NULL,        -- always JPY (null for source='en' rows)
  price_hkd     INTEGER      NULL,        -- only set for source='en' rows
  status        TEXT         NOT NULL CHECK (status IN ('sold', 'listed')),
  listing_id    TEXT         NULL,        -- SNKRDUNK ULID, only for source='en'
  apparel_id    TEXT         NULL,        -- SNKRDUNK product id, for debugging
  scraped_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON price_history TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON price_history TO service_role;

CREATE INDEX IF NOT EXISTS idx_price_history_card_date
  ON price_history(card_id, observed_date DESC);
CREATE INDEX IF NOT EXISTS idx_price_history_apparel_date
  ON price_history(apparel_id, observed_date DESC);
CREATE INDEX IF NOT EXISTS idx_price_history_card_condition_date
  ON price_history(card_id, condition, observed_date DESC);

-- 3. Watchlist (per user)
CREATE TABLE IF NOT EXISTS watchlist (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  card_id TEXT NOT NULL REFERENCES master_table(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, card_id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON watchlist TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON watchlist TO service_role;

-- 4. Transactions (per user)
CREATE TABLE IF NOT EXISTS transactions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  card_id TEXT NOT NULL REFERENCES master_table(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('buy', 'sell')),
  condition TEXT NOT NULL CHECK (condition IN ('PSA10', 'TAG10', 'RAW_A')),
  price INTEGER NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  date DATE NOT NULL,
  notes TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON transactions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON transactions TO service_role;

-- ============================================
-- Row Level Security (RLS) Policies
-- ============================================

-- Master table: readable by all authenticated users
ALTER TABLE master_table ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Master table is viewable by authenticated users"
  ON master_table FOR SELECT
  TO authenticated
  USING (true);

-- Price history: readable by all authenticated users
ALTER TABLE price_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Price history viewable by authenticated users"
  ON price_history FOR SELECT
  TO authenticated
  USING (true);

-- Watchlist: users can only see/modify their own
ALTER TABLE watchlist ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own watchlist"
  ON watchlist FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own watchlist"
  ON watchlist FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own watchlist"
  ON watchlist FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- Transactions: users can only see/modify their own
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own transactions"
  ON transactions FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own transactions"
  ON transactions FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own transactions"
  ON transactions FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own transactions"
  ON transactions FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- ============================================
-- Service role policies for scraper
-- (The scraper uses service_role key, which bypasses RLS)
-- ============================================
